### ISSUE TITLE
Startup errors after login

### ISSUE THREAD

**Issue by dbgjerez** [dbgjerez/jenkins-ci#4]
Después de iniciar sesión muestra varios fallos de seguridad

**Comment by JuanmaBM** [comment]
To resolve this issue we have used this resources:

- To disable remote cli warning: Java argument solution in https://support.cloudbees.com/hc/en-us/articles/234709648-Disable-Jenkins-CLI
- To enable CSRF protection use post-init script from https://wiki.jenkins.io/display/JENKINS/CSRF+Protection
- To disable deprecated JNLP protocols use script from https://github.com/samrocketman/jenkins-bootstrap-shared/blob/master/scripts/configure-jnlp-agent-protocols.groovy
